#!/usr/bin/env python

import time
import rospy # pylint: disable=import-error
from sensor_msgs.msg import JointState # pylint: disable=import-error
from frystation.srv import GetJointPose # pylint: disable=import-error

def joint_states_topic_callback(data):
	global MANIPULATOR_JOINT_STATES
	MANIPULATOR_JOINT_STATES.name =  data.name
	MANIPULATOR_JOINT_STATES.position =  data.position

def joint_state_service_callback(request):
	print("Returning the following Manipulator joint angles: ")
	print(MANIPULATOR_JOINT_STATES.position)
	return(MANIPULATOR_JOINT_STATES.name, MANIPULATOR_JOINT_STATES.position)

def manipulator_joint_position_service():
	rospy.init_node('joint_position_server')
	_s = rospy.Service('get_joint_values', GetJointPose, joint_state_service_callback)
	print("Ready to recieve manipulator joint state requests")
	rospy.spin()

if __name__ == "__main__":
	MANIPULATOR_JOINT_STATES = JointState()
	#setup a subscriber to get joint states, allow 1 second for subscriber to register
	rospy.Subscriber("/open_manipulator_pro/joint_states", JointState, joint_states_topic_callback)
	time.sleep(2) 
	manipulator_joint_position_service()
